import { ProductModel } from '@designer-glasses/libs/models/Products/products.interface';
export const products: ProductModel[] = [
  {
    id: '1',
    name: 'GUCCI 1010',
    frameType: ['Rimless', 'Half Rimless'],
    shape: ['oval', 'rectangle'],
    prices:['300Rs','200Rs','400Rs'],
    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    warranties:['Free Lenses Anti Reflection','Money Back Grantee','Free Shipping'],

    advertisment: {
      link: '',
      title: 'Armani 2020',
      tryOn: true,
      type: 'new',
    },
    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },
  {
    id: '2',
    frameType: ['Rimless', 'Half Rimless'],
    shape: ['oval', 'rectangle'],
    prices:['300Rs','200Rs'],
    name: 'GUCCI 1010',
    warranties:['Free Lenses Anti Reflection','Money Back Grantee','Free Shipping'],

    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    advertisment: {
      link: '',
      title: '',
      tryOn: true,
      type: 'sale',
    },
    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },
  {
    frameType: ['Rimless', 'Half Rimless'],
    id: '1',
    shape: ['oval', 'rectangle'],

    name: 'GUCCI 1010',
    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    advertisment: {
      link: '',
      title: '',
      tryOn: false,
      type: '',
    },

    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },
  {
    id: '1',
    frameType: ['Rimless', 'Half Rimless'],
    shape: ['oval', 'rectangle'],

    name: 'GUCCI 1010',
    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    advertisment: {
      link: '',
      title: '',
      tryOn: false,
      type: 'sale',
    },
    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },
  {
    id: '1',
    frameType: ['Rimless', 'Half Rimless'],
    shape: ['oval', 'rectangle'],

    name: 'GUCCI 1010',
    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    advertisment: {
      link: '',
      title: '',
      tryOn: false,
      type: 'sale',
    },
    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },
  {
    id: '1',
    frameType: ['Rimless', 'Half Rimless'],
    shape: ['oval', 'rectangle'],

    name: 'GUCCI 1010',
    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    advertisment: {
      link: '',
      title: 'Armani 2020',
      tryOn: false,
      type: 'new',
    },
    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },
  {
    id: '1',
    frameType: ['Rimless', 'Half Rimless'],
    shape: ['oval', 'rectangle'],

    name: 'GUCCI 1010',
    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    advertisment: {
      link: '',
      title: 'Armani 2020',
      tryOn: false,
      type: 'new',
    },
    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },
  {
    id: '1',
    frameType: ['Rimless', 'Half Rimless'],
    shape: ['oval', 'rectangle'],

    name: 'GUCCI 1010',
    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    advertisment: {
      link: '',
      title: 'Armani 2020',
      tryOn: false,
      type: 'new',
    },
    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },  {
    id: '1',
    frameType: ['Rimless', 'Half Rimless'],
    shape: ['oval', 'rectangle'],

    name: 'GUCCI 1010',
    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    advertisment: {
      link: '',
      title: 'Armani 2020',
      tryOn: false,
      type: 'new',
    },
    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },  {
    id: '1',
    frameType: ['Rimless', 'Half Rimless'],
    shape: ['oval', 'rectangle'],

    name: 'GUCCI 1010',
    images: [
      'https://www.clipartmax.com/png/middle/429-4293095_geni-glasses-pictures-of-eyeglasses-clip-art-reading-glasses-transparent-background.png',
      'https://www.pngfind.com/pngs/m/1-13037_semi-transparent-glasses-transparent-background-glasses-hd-png.png',
      'https://png.pngtree.com/png-vector/20201011/ourmid/pngtree-simple-style-elegant-black-glasses-png-image_2351998.jpg',
    ],
    advertisment: {
      link: '',
      title: 'Armani 2020',
      tryOn: false,
      type: 'new',
    },
    genders: ['men', 'women', 'childrens'],
    sku: ['xl', 'lg', 'sm'],
    colors: ['#ff2f3f', '#f0af3f', '#afdf0a'],
    date: 'today',
  },
];
